# アプリケーションのID
application: tomato--feed

# アプリケーションのバージョン
version: 1-2

# ランタイムの名称。現時点では「python」のみ
runtime: python

# アプリケーションが前提としているAPIのバージョン
api_version: 1

# URLと、その処理方法の定義
handlers:
- url: /styles
  static_dir: styles
- url: /images
  static_dir: images
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: tomato.py