runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /styles
  static_dir: styles
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always
- url: /.*
  script: tomato.app
  secure: always
